// User
export const ERROR_RECEIVE_USER = "ERROR_RECEIVE_USER";
export const REQUEST_USER = "REQUEST_USER";
export const RECEIVE_USER = "RECEIVE_USER";

export const ERROR_SIGN_IN = "ERROR_SIGN_IN";
export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SUCCESS_SIGN_IN = "SUCCESS_SIGN_IN";

export const ERROR_SIGN_UP = "ERROR_SIGN_UP";
export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";

export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";

//Books

export const ADD_BOOKS_LOADING = "ADD_BOOKS_LOADING";
export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS";
export const ADD_BOOKS_ERROR = "ADD_BOOKS_ERROR";

export const FETCH_BOOKS_LOADING = "FETCH_BOOKS_LOADING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";

export const DELETE_BOOKS_LOADING = "DELETE_BOOKS_LOADING";
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_ERROR = "DELETE_BOOKS_ERROR";

export const FETCH_BOOK_LOADING = "FETCH_BOOK_LOADING";
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_BOOK_ERROR = "FETCH_BOOK_ERROR";

export const UPDATE_BOOK_LOADING = "UPDATE_BOOK_LOADING";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_ERROR = "UPDATE_BOOK_ERROR";

//Filter
export const SET_FILTER = "SET_FILTER";
