export const REGISTRATION_EMAIL_ALREADY_EXISTS = 'REGISTRATION_EMAIL_ALREADY_EXISTS';
export const REGISTRATION_LOGIN_ALREADY_EXISTS = 'REGISTRATION_LOGIN_ALREADY_EXISTS';
export const WRONG_LOGIN_OR_PASSWORD = 'WRONG_LOGIN_OR_PASSWORD';
